apiVersion: apps/v1
kind: Deployment
metadata:
  name: hosting
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: hosting
  template:
    metadata:
      labels:
        app: hosting
    spec:
        containers:
        - image: micalgenus/hosting:{{ .Chart.AppVersion }}
          imagePullPolicy: Always
          name: hosting
          env:
            - name: MYSQL_HOST
              value: hosting-redis.{{ .Release.Namespace }}.svc.cluster.local
            - name: MYSQL_PORT
              value: {{ 6379 | quote }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: hosting
spec:
  selector:
    app: hosting
  ports:
    - name: express
      port: 3000
      targetPort: 3000
