apiVersion: apps/v1
kind: Deployment
metadata:
  name: hosting-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hosting-redis
  template:
    metadata:
      labels:
        app: hosting-redis
    spec:
      containers:
        - image: redis
          imagePullPolicy: Always
          name: hosting-redis

---
apiVersion: v1
kind: Service
metadata:
  name: hosting-redis
spec:
  selector:
    app: hosting-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
