apiVersion: v1
kind: ServiceAccount
metadata:
  name: hosting

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hosting-sa-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]

# ---
# kind: RoleBinding
# apiVersion: rbac.authorization.k8s.io/v1
# metatdata:
#   name: hosting-sa-role-binding
#   namespace: {{ .Release.Namespace }}
# subjects:
# - kind: ServiceAccount
#   name: hosting
#   namespace: {{ .Release.Namespace }}
# roleRef:
#   kind: Role
#   name: hosting-sa-role
#   apiGroup: rbac.authorization.k8s.io
